// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydtrjeubpsgmrnhvppzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkdHJqZXVicHNnbXJuaHZwcHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTM1NjYsImV4cCI6MjA2MTU2OTU2Nn0.Ra87DtAPabc1C959CLw81v2SUBBnAB3n0zsjAxKrVWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);